### PR TITLE
Add option for user to save password permanently

### PR DESCRIPTION
**Pull request by Skycam3014**
This PR refactors some of the password caching logic to allow saving of the users password as a preference alongside `username`. Also adds a checkbox toggle (see below) between this behavior and the previous caching behavior for that stored the password for `password-keep-minutes` or until DrRacket was closed. 

Only caching passwords temporarily makes complete sense on shared computers but it doesn't seem to particularly be a security risk on an individual's personal device. It also shouldn't be unreasonable to add a configuration option in `info.rkt` for instructors to disable/enable this behavior entirely.

I'm a uni student taking a course using handin right now and I originally made this fork out of my own frustration after retyping my password for probably the 1000th time. I showed an earlier version of these changes to @ccshan and he encouraged me to make this PR. 

Constructive criticism is welcome!

handin

### CODE REVIEW

**Comment by samth** [comment]
Do other people who run handin have any thoughts here? @elibarzilay @mflatt @JoeyEremondi

**Comment by ebarzilay-godaddy** [comment]
A little bit of a long answer.  I'll try to use bullets to make it shorter.

* I have enough changes of my own, that I will probably not get this change, so take the rest as just an opinion.

* I think that this is NOT a good idea, for the usual security reasons: I ask students to put in a password, some will inevitably reuse existing passwords, so if I allow them to get this password saved in cleartext, then I'm creating a security risk for them.  (And I know the usual arguments: it's my machine, and I know it's safe etc...)

* So, from a security POV, this would be a good change ONLY if it uses some OS keychain tool to save the password, so it's not just cleartext.  But that would be a whole PITA in itself given the different ways that Windows/Macs/Linux implement that.  (But if it's done, then it would make sense to always store it, of course.)

* In fact, one of the things that make me worried about the current code (which I was too lazy to do something about) is the fact that passwords are only MD5-ed instead of something less breakable.

* You could also just make it a `config.rktd` setting (maybe even an `info.rkt`, which is slightly more open for user hacking), so that the instructor can decide whether to allow it or not.  Some instructors (@ccshan, probably 😃) would supposedly turn it on and warn the students about the implications.  This way, the possible fault is rolled onto the instructor, which rolls it onto the students. 

  Practically, most students will turn it on, which is exactly the problem here...

* Finally, another consideration here is the web server -- except that browsers usually know how to handle that safely, so it's less annoying than the racket client.

**Comment by LeifAndersen** [comment]
Not that anyone asked, but I have to agree with @elibarzilay here.

Without having done a security audit of how the password here is getting saved, I _highly_ suspect its hugely vulnerable UNLESS its using the host systems keyring facilities. (In which case I'm more okay with it.)

Probably a better (although probably harder to implement) alternative is to use something like OAuth, which could potentially let the user also use whatever (hopefully more secure) existing password manager they are already using.

**Comment by Skycam3014** [comment]
Lots of feedback -- thank you both! 

I hadn't considered that most students would inevitably enable this on a shared computer and likely reuse an existing password. In that situation, saving their password in cleartext obviously becomes a major security issue. I think it's a direct consequence of my naivety regarding actual user behavior that I didn't adequately consider the risk of not using the os's keyring or oauth. While I'm personally comfortable using cleartext to store a password I use only for handin on my own machine, in practicality that's just simply not the situation that most students would put themselves in, is it. 

I'm going to go ahead and close this PR now. Thank you again for the thorough criticism, as this was my first ever pull request, thank you for the valuable experience.

**Comment by ebarzilay-godaddy** [comment]
@LeifAndersen -- the "password caching" thing is something that I think that I added, and it should probably be kept in memory only.  I see now that there is a configurable `password-keep-minutes` setting, but it's still in memory, so should be "safe enough".

@Skycam3014 -- I didn't mean that this is because of using a shared machine...  In fact, I think that the days of students working on some shared lab machines are mostly gone.  The problem is: I'm lazy, so I use the same google/university/whatever password for the handin server, it gets saved in the file, someone breaks into my machine and grabs that file, now they have access to all of these things.

---

BTW, I think that a JWT should be easier to setup than some oauth thing, and I thought about looking into that a few times.  But every time I thought about it, I concluded that it's a losing race, and instead, I'd shoot for re-implementing the whole thing as a web-first kind of a thing:

* Make the server component have an upload "api endpoint" thing, which saves a file. Use it in the web pages to allow uploading from them.
* Change the handin server functionality to just listen for a FS event of a file saved, and run the tests on that.  (Needs to rethink interactions with the user, but could simplify things to make it one-way: give up things like yes/no dialogs.)
* Make the DrR side use the same api to submit files.

One immediate profit of that is that you can do everything using just the web interface.  Authentication becomes trivial since the browser has about a 100 ways of dealing with that easily (DrR might need some stuff, possibly firing a web page to get a token and then saving *that* locally in the style of "remember this device").

It's also something that would cater for the inevitable small number of students that want to use SomeOtherEditor.

It should also be possible to re-implement it in a "more api-ish" kind of way: instead of constructing HTML, it should just return some JSON which would be rendered by the browser or whatever.  (I do that currently in a horrible way: there's a JS code injected into the page which parses the HTML and adds a pile of stuff to it.)

It would also make it easier to make the interactions better: instead of plugging into the racket web server, it could be a more common single page app thing (or anything really, if the actual information is just the json data).  This resolves things that have ancient smell: the racket web server makes it possible to have a long running process, and talk to it via continuations, but the only long-lived state is just the authentication, so there's no need for that --- and at the same time, it has some strange by-products (go to the login page, and keep it open for a while, and any login attempts will fail because the process timed out).

And finally, another kind of old-smelling bit is that the current layout separates interacting with my class web pages and interacting with the handin server.  If it's just an api kind of a thing, I could show you your grade when you look at the homework text, or I can show you the posted solution only if you're logged in, so it's not publicly available, etc.  Basically making the whole thing feel more like a coherent thing rather than a collection of different parts...

**Comment by Skycam3014** [comment]
Thank you @ebarzilay-godaddy for the clarification. While the risk of a targeted attack on a machine to grab someones handin password is probably low, I agree with you that there's reason to be complacent with security. It's actually dawning on me now that even if an instructor didn't reuse their handin password for anything else, a situation where a student managed to get access to the handin server would still be problematic. 

In regards to the rest of your comment: For me, initially this started as a client-only thing as I wasn't planning on making a PR. I've spent some time skimming over the handin-server code now and your api reimplementation makes a lot of sense. I like that it would also open possibilities for a handin extension for VSCode etc. I also found all your information on the inner workings of the server fascinating. 

My interest is piqued and I'm sure I'll end up looking into your ideas at some point in the future. I'll leave this PR closed for now as I don't want take on more than I can handle on top of my coursework at the moment. If I end up coming up with something presentable, I'll consider reopening this or making a new PR even if just for feedback.

Thank you for being so welcoming!

**Comment by ebarzilay-godaddy** [comment]
* It's wrong to think along the lines of "unlikely that someone will break in to get your handin credentials": instead, think about mass-scraping your files, and then feeding all of the high-entropy strings into some password hacking tool.

* Yes, breaking into the server could be a problem, since the hashes are md5, which is not difficult to break via brute-force.

* As a general note, I've had multiple students now that wanted to have a DrR-independent tool for submission, and the interactive nature of the protocol is what made it grind to a halt every time.

* And finally, if you want to spend time doing some of these things, I'll be happy to discuss it further.  As you can see, there's no shortage of places to sink time into :)

**Pull request closed without merging**
