### PR TITLE
Add a new `extra-dispatcher-file' configuration option.

### PR DESCRIPTION
**Pull request by elibarzilay**
This allows handling other requests implement additional course-related
functionality by the already running server.  The documentation needs
more work though: it refers to `dispatcher/c' which needs to be added,
and there is no real sample code for it.  (My use is too specific to be
used.)

### CODE REVIEW

**Comment by samth** [comment]
@elibarzilay Is this likely to be worked on in the future, or should I fix up the docs, or should it be closed?

**Comment by elibarzilay** [comment]
I think that it's mostly fine, with really small things:

* the typo that albertxing pointed at,

* adding whatever require line to get the `dispatcher/c` binding,

* the "example" could be better.

The reason for this addition is that if you want to handle other things,
you need to either add another separate web server (obviously bad), or
somehow wrap this one (complicated, since it can deal with both http and
the handin protocol).

**Comment by samth** [comment]
@elibarzilay Will you make those changes, or do you want me to?

**Comment by elibarzilay** [comment]
Superseded by #41.

(And better to merge as-is, and add the doc tweaks when needed in the future...?)

**Pull request closed without merging**
